/**
* Strava API v3
* The [Swagger Playground](https://developers.strava.com/playground) is the easiest way to familiarize yourself with the Strava API by submitting HTTP requests and observing the responses before you write any client code. It will show what a response will look like with different endpoints depending on the authorization scope you receive from your athletes. To use the Playground, go to https://www.strava.com/settings/api and change your “Authorization Callback Domain” to developers.strava.com. Please note, we only support Swagger 2.0. There is a known issue where you can only select one scope at a time. For more information, please check the section “client code” at https://developers.strava.com/docs.
*
* OpenAPI spec version: 3.0.0
* 
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/
package io.swagger.client.models

import io.swagger.client.models.SummaryAthlete
import io.swagger.client.models.SummaryClub
import io.swagger.client.models.SummaryGear

/**
 * 
 * @param followerCount The athlete's follower count.
 * @param friendCount The athlete's friend count.
 * @param measurementPreference The athlete's preferred unit system.
 * @param ftp The athlete's FTP (Functional Threshold Power).
 * @param weight The athlete's weight.
 * @param clubs The athlete's clubs.
 * @param bikes The athlete's bikes.
 * @param shoes The athlete's shoes.
 */
data class DetailedAthlete (
    /* The athlete's follower count. */
    val followerCount: kotlin.Int? = null,
    /* The athlete's friend count. */
    val friendCount: kotlin.Int? = null,
    /* The athlete's preferred unit system. */
    val measurementPreference: MeasurementPreference? = null,
    /* The athlete's FTP (Functional Threshold Power). */
    val ftp: kotlin.Int? = null,
    /* The athlete's weight. */
    val weight: kotlin.Float? = null,
    /* The athlete's clubs. */
    val clubs: kotlin.Array<SummaryClub>? = null,
    /* The athlete's bikes. */
    val bikes: kotlin.Array<SummaryGear>? = null,
    /* The athlete's shoes. */
    val shoes: kotlin.Array<SummaryGear>? = null,
) {






    /**
    * The athlete's preferred unit system.
    * Values: FEET,METERS
    */
    enum class MeasurementPreference(val value: kotlin.String){
    
        FEET("feet"),
    
        METERS("meters");
    
    }












}

