/**
* Strava API v3
* The [Swagger Playground](https://developers.strava.com/playground) is the easiest way to familiarize yourself with the Strava API by submitting HTTP requests and observing the responses before you write any client code. It will show what a response will look like with different endpoints depending on the authorization scope you receive from your athletes. To use the Playground, go to https://www.strava.com/settings/api and change your “Authorization Callback Domain” to developers.strava.com. Please note, we only support Swagger 2.0. There is a known issue where you can only select one scope at a time. For more information, please check the section “client code” at https://developers.strava.com/docs.
*
* OpenAPI spec version: 3.0.0
* 
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/
package io.swagger.client.models

import io.swagger.client.models.LatLng

/**
 * 
 * @param latlng The location along the route that the waypoint is closest to
 * @param targetLatlng A location off of the route that the waypoint is (optional)
 * @param categories Categories that the waypoint belongs to
 * @param title A title for the waypoint
 * @param description A description of the waypoint (optional)
 * @param distanceIntoRoute The number meters along the route that the waypoint is located
 */
data class Waypoint (
    /* The location along the route that the waypoint is closest to */
    val latlng: LatLng? = null,
    /* A location off of the route that the waypoint is (optional) */
    val targetLatlng: LatLng? = null,
    /* Categories that the waypoint belongs to */
    val categories: kotlin.Array<kotlin.String>? = null,
    /* A title for the waypoint */
    val title: kotlin.String? = null,
    /* A description of the waypoint (optional) */
    val description: kotlin.String? = null,
    /* The number meters along the route that the waypoint is located */
    val distanceIntoRoute: kotlin.Int? = null,
) {

}

