/*
 * Strava API v3
 * The [Swagger Playground](https://developers.strava.com/playground) is the easiest way to familiarize yourself with the Strava API by submitting HTTP requests and observing the responses before you write any client code. It will show what a response will look like with different endpoints depending on the authorization scope you receive from your athletes. To use the Playground, go to https://www.strava.com/settings/api and change your “Authorization Callback Domain” to developers.strava.com. Please note, we only support Swagger 2.0. There is a known issue where you can only select one scope at a time. For more information, please check the section “client code” at https://developers.strava.com/docs.
 *
 * OpenAPI spec version: 3.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * ClubAthlete
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2025-05-20T09:05:48.485+02:00")
public class ClubAthlete {
  @SerializedName("resource_state")
  private Integer resourceState = null;

  @SerializedName("firstname")
  private String firstname = null;

  @SerializedName("lastname")
  private String lastname = null;

  @SerializedName("member")
  private String member = null;

  @SerializedName("admin")
  private Boolean admin = null;

  @SerializedName("owner")
  private Boolean owner = null;

  public ClubAthlete resourceState(Integer resourceState) {
    this.resourceState = resourceState;
    return this;
  }

   /**
   * Resource state, indicates level of detail. Possible values: 1 -&gt; \&quot;meta\&quot;, 2 -&gt; \&quot;summary\&quot;, 3 -&gt; \&quot;detail\&quot;
   * @return resourceState
  **/
  @ApiModelProperty(value = "Resource state, indicates level of detail. Possible values: 1 -> \"meta\", 2 -> \"summary\", 3 -> \"detail\"")
  public Integer getResourceState() {
    return resourceState;
  }

  public void setResourceState(Integer resourceState) {
    this.resourceState = resourceState;
  }

  public ClubAthlete firstname(String firstname) {
    this.firstname = firstname;
    return this;
  }

   /**
   * The athlete&#39;s first name.
   * @return firstname
  **/
  @ApiModelProperty(value = "The athlete's first name.")
  public String getFirstname() {
    return firstname;
  }

  public void setFirstname(String firstname) {
    this.firstname = firstname;
  }

  public ClubAthlete lastname(String lastname) {
    this.lastname = lastname;
    return this;
  }

   /**
   * The athlete&#39;s last initial.
   * @return lastname
  **/
  @ApiModelProperty(value = "The athlete's last initial.")
  public String getLastname() {
    return lastname;
  }

  public void setLastname(String lastname) {
    this.lastname = lastname;
  }

  public ClubAthlete member(String member) {
    this.member = member;
    return this;
  }

   /**
   * The athlete&#39;s member status.
   * @return member
  **/
  @ApiModelProperty(value = "The athlete's member status.")
  public String getMember() {
    return member;
  }

  public void setMember(String member) {
    this.member = member;
  }

  public ClubAthlete admin(Boolean admin) {
    this.admin = admin;
    return this;
  }

   /**
   * Whether the athlete is a club admin.
   * @return admin
  **/
  @ApiModelProperty(value = "Whether the athlete is a club admin.")
  public Boolean isAdmin() {
    return admin;
  }

  public void setAdmin(Boolean admin) {
    this.admin = admin;
  }

  public ClubAthlete owner(Boolean owner) {
    this.owner = owner;
    return this;
  }

   /**
   * Whether the athlete is club owner.
   * @return owner
  **/
  @ApiModelProperty(value = "Whether the athlete is club owner.")
  public Boolean isOwner() {
    return owner;
  }

  public void setOwner(Boolean owner) {
    this.owner = owner;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ClubAthlete clubAthlete = (ClubAthlete) o;
    return Objects.equals(this.resourceState, clubAthlete.resourceState) &&
        Objects.equals(this.firstname, clubAthlete.firstname) &&
        Objects.equals(this.lastname, clubAthlete.lastname) &&
        Objects.equals(this.member, clubAthlete.member) &&
        Objects.equals(this.admin, clubAthlete.admin) &&
        Objects.equals(this.owner, clubAthlete.owner);
  }

  @Override
  public int hashCode() {
    return Objects.hash(resourceState, firstname, lastname, member, admin, owner);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ClubAthlete {\n");
    
    sb.append("    resourceState: ").append(toIndentedString(resourceState)).append("\n");
    sb.append("    firstname: ").append(toIndentedString(firstname)).append("\n");
    sb.append("    lastname: ").append(toIndentedString(lastname)).append("\n");
    sb.append("    member: ").append(toIndentedString(member)).append("\n");
    sb.append("    admin: ").append(toIndentedString(admin)).append("\n");
    sb.append("    owner: ").append(toIndentedString(owner)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

